[package]
name = "mongodb-vs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4"
exasol-udf-sdk = "=0.21.3"
exasol-udf-macros = "=0.21.3"
futures-util = "0.3"
mongodb = { version = "3.8.0", default-features = false, features = ["compat-3-3-0", "bson-2", "rustls-tls", "dns-resolver"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["rt"] }
